* Apps created during my Android class
The class was fun, it primarily worked on Java. 
I will have to sort out problems with running a local android emulator.

* Portfolios
1 - [[portfolio1][Calculator]]

2- [[portfolio2][Calculator, auto generating results. Changing activities]]

3 - [[portfolio3][Calculator, auto generating results. Slide bar]]

4 - [[portfolio4a][Buttons - The buttons openn the browser, phone, camera]]

5 - [[portfolio5][Spinners input]]

6 - [[portfolio6][Changing activities, displaying error messages?]]

7 - [[portfolio7][TBD]]

8 - [[portfolio8][Plays mp3 files with a button and a picture denoting the sound]]

9 - [[portfolio9][Tic tac toe]]

10a - [[portfolio10a_sliding][Sliding - Transitions activities by sliding]]

10b - [[portfolio10b_scenes][Press button, display pictures]]

11 - [[portfolio11][Landscape/Portrait mode, changing background color?]]

12 - [[portfolio12][Counter (non-stop)]]

13 - [[portfolio13][Bouncing ball]]

14 - [[portfolio14_letters][Letter balls?]]

15 - [[portfolio15][Database]]

* Projects

Midterm - [[midterm][Auto updating conversion app]]

Weather - [[weatherproject][Searches location, display weather info (manual)]]

Assignment 3 - [[assignment3][Display image from drop down menu]]

Assignment 4 - [[assignment4][Plays mp3 by pressing buttons]]

